services:
  web:
    image: php:apache
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
    environment:
      VAR1: "sóc una pera i estic al docker-compose"
      VAR2: ${VAR2}
    depends_on:
      - db

  db:
    image: mysql:9.3
    environment:
      MYSQL_ROOT_PASSWORD: passwordDeRootQueNoShaDeFerServirMai
      MYSQL_DATABASE: a24ikematgar_incidencia
      MYSQL_USER: a24ikematgar_incidencia
      MYSQL_PASSWORD: :8VBky{Uq9D^W-xk
    #    El mysql no s'exposa a l'exterior
    #    L'aplicació web hi accedirà per la xarxa interna de docker
    #    ports:
    #      - "3306:3306"

    # La carpeta de mysql ha d'estar al .gitignore per no pujar-la al repositori
    volumes:
      - ./db_data:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - db